from app.schemas.base import Schema
from app.schemas.budget import BudgetLimitCreate, BudgetLimitRead, BudgetProgress
from app.schemas.category import CategoryCreate, CategoryRead
from app.schemas.report import AnalyticsSummary, CategoryBreakdown
from app.schemas.transaction import TransactionCreate, TransactionRead
from app.schemas.user import UserCreate, UserRead
from app.schemas.webapp import (
    WebHeatmapCell,
    WebInsightsResponse,
    WebMerchantGroup,
    WebAssistantRequest,
    WebAssistantResponse,
    WebAssistantFeedbackRequest,
    WebAssistantFeedbackResponse,
    WebConfigResponse,
    WebChartResponse,
    WebChartSeries,
    WebCategory,
    WebPreferencesResponse,
    WebPreferencesUpdate,
    WebOverviewResponse,
    WebReceiptRequest,
    WebReceiptResponse,
    WebSessionRequest,
    WebSessionResponse,
    WebTransactionCreate,
    WebTransactionUpdate,
    WebTransactionListItem,
    WebStatementImportRequest,
    WebStatementImportResponse,
)

__all__ = [
    "Schema",
    "BudgetLimitCreate",
    "BudgetLimitRead",
    "BudgetProgress",
    "CategoryCreate",
    "CategoryRead",
    "AnalyticsSummary",
    "CategoryBreakdown",
    "TransactionCreate",
    "TransactionRead",
    "UserCreate",
    "UserRead",
    "WebSessionRequest",
    "WebSessionResponse",
    "WebTransactionCreate",
    "WebTransactionUpdate",
    "WebTransactionListItem",
    "WebOverviewResponse",
    "WebAssistantRequest",
    "WebAssistantResponse",
    "WebAssistantFeedbackRequest",
    "WebAssistantFeedbackResponse",
    "WebConfigResponse",
    "WebChartSeries",
    "WebChartResponse",
    "WebReceiptRequest",
    "WebReceiptResponse",
    "WebStatementImportRequest",
    "WebStatementImportResponse",
    "WebInsightsResponse",
    "WebHeatmapCell",
    "WebMerchantGroup",
    "WebCategory",
    "WebPreferencesUpdate",
    "WebPreferencesResponse",
]
